:traffic_light: Exit workflow when `GHCR_PAT` is not set

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,7 +6,14 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - run: exit 0
+    - name: Check for presence of mandatory GHCR_PAT secret
+      env:
+        GHCR_PAT: ${{ secrets.GHCR_PAT }}
+      run: |
+        if [[ ! -z "$GHCR_PAT" ]]; then
+          echo "::error file=README.md,line=41,col=1::A GHCR_PAT secret is required."
+          exit 1
+        fi
     - uses: actions/checkout@v2
     - name: Build & Publish If Tagged
       uses: docker/build-push-action@v1
